###############################################################
# Argentina Dengue Analysis
# Script: 19_build_season_temporal_descriptors.R
# Purpose: Build deterministic national and regional season descriptors.
###############################################################

abort_c19 <- function(message) stop(message, call. = FALSE)
read_c19 <- function(path) { x <- readr::read_csv(path, show_col_types=FALSE); if(nrow(readr::problems(x))) abort_c19(paste("Invalid CSV:",path)); x }
publish_c19 <- function(x,path) { dir.create(dirname(path),recursive=TRUE,showWarnings=FALSE); tmp<-tempfile(".c19_",dirname(path),".tmp"); on.exit(unlink(tmp),add=TRUE); readr::write_csv(x,tmp,na=""); if(!file.rename(tmp,path)) abort_c19(paste("Could not publish:",path)) }
peak_c19 <- function(x, metric) {
  z<-x[x[[metric]]==max(x[[metric]]),c("season_week_index","source_year","source_week"),drop=FALSE]; idx<-sort(z$season_week_index)
  list(value=max(x[[metric]]),status=if(nrow(z)==1)"unique_peak" else "tie_present",tie_count=nrow(z),tied=as.character(paste(idx,collapse="|")),index=if(nrow(z)==1)z$season_week_index[[1]] else NA_integer_,year=if(nrow(z)==1)z$source_year[[1]] else NA_integer_,week=if(nrow(z)==1)z$source_week[[1]] else NA_integer_)
}
alignment_c19 <- function(a,b) if(a$status=="tie_present"||b$status=="tie_present")"tie_present" else if(a$index==b$index)"same_week" else "different_week"
median_c19 <- function(x) { x<-dplyr::arrange(x,season_week_index); x[which(cumsum(x$published_case_count)>=sum(x$published_case_count)/2)[1],c("season_week_index","source_year","source_week")] }
windows_c19 <- function(x,target) { total<-sum(x$published_case_count); candidates<-list();k<-1L; for(i in seq_len(nrow(x)))for(j in i:nrow(x)){v<-sum(x$published_case_count[i:j]);if(v/total>=target){candidates[[k]]<-tibble::tibble(start=i,end=j,length=j-i+1,cases=v,share=v/total);k<-k+1L}}; q<-dplyr::bind_rows(candidates)|>dplyr::arrange(length,dplyr::desc(share),start)|>dplyr::slice(1); tibble::tibble(target_share=target,window_start_season_week_index=x$season_week_index[q$start],window_end_season_week_index=x$season_week_index[q$end],window_length_weeks=q$length,window_published_case_count=q$cases,window_published_case_share=q$share,start_source_year=x$source_year[q$start],start_source_week=x$source_week[q$start],end_source_year=x$source_year[q$end],end_source_week=x$source_week[q$end]) }
tied_index_columns_c19 <- function(x) grep("_tied_season_week_indices$", names(x), value=TRUE)
validate_tied_index_columns_c19 <- function(x) { columns<-tied_index_columns_c19(x); if(length(columns)&&!all(vapply(x[columns],is.character,logical(1))))abort_c19("Tied season-week indices must be character.") }
read_descriptor_qa_c19 <- function(path, tied_columns) { types<-do.call(readr::cols,c(stats::setNames(rep(list(readr::col_character()),length(tied_columns)),tied_columns),list(.default=readr::col_guess()))); x<-readr::read_csv(path,col_types=types,show_col_types=FALSE); if(!all(vapply(x[tied_columns],is.character,logical(1))))abort_c19(paste("Descriptor tied-index type QA failed:",path)); x }

#' Build all C.19 outputs in memory before atomic publication.
main <- function(){
 c<-yaml::read_yaml("config/project.yml");a<-c$artifacts;n<-read_c19(a$season_weekly_national);r<-read_c19(a$season_weekly_region);ns<-read_c19(a$season_national_summary);rs<-read_c19(a$season_region_summary);g<-read_c19(a$season_geographic_validation_snapshot)
 nc<-dplyr::filter(n,denominator_scenario=="contemporary")|>dplyr::arrange(season_week_index); nsi<-dplyr::filter(n,denominator_scenario=="sensitivity_interannual")|>dplyr::arrange(season_week_index)
 if(nrow(nc)!=52||!identical(as.integer(nc$season_week_index),1:52)||!identical(nc[c("season_week_index","source_year","source_week","published_row_count","published_case_count")],nsi[c("season_week_index","source_year","source_week","published_row_count","published_case_count")]))abort_c19("National C.18 invariance or axis failed.")
 rc<-dplyr::filter(r,denominator_scenario=="contemporary"); ri<-dplyr::filter(r,denominator_scenario=="sensitivity_interannual"); key<-c("season_week_index","epidemiological_region"); if(!identical(dplyr::arrange(rc,season_week_index,epidemiological_region)[c(key,"published_row_count","published_case_count")],dplyr::arrange(ri,season_week_index,epidemiological_region)[c(key,"published_row_count","published_case_count")]))abort_c19("Regional numerator invariance failed.")
 national_published_row_count<-sum(nc$published_row_count); national_published_case_count<-sum(nc$published_case_count); national_observed_week_count<-dplyr::n_distinct(nc$season_week_index)
 if(national_published_row_count!=ns$season_published_row_count||national_published_case_count!=ns$season_published_case_count||national_observed_week_count!=ns$season_week_count)abort_c19("National C.18 weekly-to-summary reconciliation failed.")
 regional_bases<-rc|>dplyr::group_by(epidemiological_region)|>dplyr::summarise(regional_published_row_count=sum(published_row_count),regional_published_case_count=sum(published_case_count),regional_observed_week_count=dplyr::n_distinct(season_week_index),.groups="drop")|>dplyr::left_join(dplyr::select(rs,epidemiological_region,published_row_count,published_case_count),by="epidemiological_region")
 if(nrow(regional_bases)!=nrow(rs)||any(is.na(regional_bases$published_row_count))||any(regional_bases$regional_published_row_count!=regional_bases$published_row_count)||any(regional_bases$regional_published_case_count!=regional_bases$published_case_count))abort_c19("Regional C.18 weekly-to-summary reconciliation failed.")
 pn<-peak_c19(nc,"published_case_count"); pr<-peak_c19(nc,"published_count_rate_100k"); ps<-peak_c19(nsi,"published_count_rate_100k"); pm<-median_c19(nc); pu<-peak_c19(dplyr::mutate(nc,unknown_share=unknown_published_case_count/published_case_count),"unknown_published_case_count"); pus<-peak_c19(dplyr::mutate(nc,unknown_share=unknown_published_case_count/published_case_count),"unknown_share")
 national<-tibble::tibble(season_temporal_descriptor_schema_version="1.0.0",season_scope_id=ns$season_scope_id,season_label=ns$season_label,national_temporal_coverage_basis="complete_explicit_season_week_axis",national_published_row_count=national_published_row_count,national_published_case_count=national_published_case_count,national_observed_week_count=national_observed_week_count,peak_count_value=pn$value,peak_count_selection_status=pn$status,peak_count_tie_count=pn$tie_count,peak_count_tied_season_week_indices=pn$tied,peak_count_season_week_index=pn$index,peak_count_source_year=pn$year,peak_count_source_week=pn$week,peak_rate_value=pr$value,peak_rate_selection_status=pr$status,peak_rate_tie_count=pr$tie_count,peak_rate_tied_season_week_indices=pr$tied,peak_rate_season_week_index=pr$index,peak_rate_source_year=pr$year,peak_rate_source_week=pr$week,count_rate_peak_alignment_status=alignment_c19(pn,pr),rate_peak_sensitivity_status=alignment_c19(pr,ps),published_count_weighted_season_week=sum(nc$season_week_index*nc$published_case_count)/sum(nc$published_case_count),published_count_weighted_median_season_week=pm$season_week_index,published_count_weighted_median_source_year=pm$source_year,published_count_weighted_median_source_week=pm$source_week,peak_unknown_published_case_count=pu$value,unknown_peak_selection_status=pu$status,unknown_peak_tie_count=pu$tie_count,unknown_peak_tied_season_week_indices=pu$tied,unknown_peak_season_week_index=pu$index,unknown_peak_source_year=pu$year,unknown_peak_source_week=pu$week,peak_unknown_published_case_share=pus$value,unknown_share_peak_selection_status=pus$status,geographic_mapping_completeness_at_national_count_peak=if(pn$status=="unique_peak")nc$geographic_mapping_completeness[nc$season_week_index==pn$index] else NA_real_)
 regional<-dplyr::group_split(rc,epidemiological_region)|>lapply(function(x){x<-dplyr::arrange(x,season_week_index);pc<-peak_c19(x,"published_case_count");pt<-peak_c19(x,"published_count_rate_100k");mt<-median_c19(x);z<-if(pc$status=="unique_peak")dplyr::filter(x,season_week_index==pc$index)else x[0,];tibble::tibble(season_temporal_descriptor_schema_version="1.0.0",season_scope_id=ns$season_scope_id,season_label=ns$season_label,epidemiological_region=x$epidemiological_region[[1]],regional_temporal_coverage_basis="observed_region_weeks_only",regional_published_row_count=sum(x$published_row_count),regional_published_case_count=sum(x$published_case_count),regional_observed_week_count=dplyr::n_distinct(x$season_week_index),peak_count_value=pc$value,peak_count_selection_status=pc$status,peak_count_tie_count=pc$tie_count,peak_count_tied_season_week_indices=pc$tied,peak_count_season_week_index=pc$index,peak_count_source_year=pc$year,peak_count_source_week=pc$week,peak_rate_value=pt$value,peak_rate_selection_status=pt$status,peak_rate_tie_count=pt$tie_count,peak_rate_tied_season_week_indices=pt$tied,peak_rate_season_week_index=pt$index,peak_rate_source_year=pt$year,peak_rate_source_week=pt$week,count_rate_peak_alignment_status=alignment_c19(pc,pt),rate_peak_sensitivity_status=alignment_c19(pt,peak_c19(dplyr::filter(ri,epidemiological_region==x$epidemiological_region[[1]]),"published_count_rate_100k")),peak_count_lag_vs_national=if(pc$status=="unique_peak"&&pn$status=="unique_peak")pc$index-pn$index else NA_integer_,published_count_weighted_season_week=sum(x$season_week_index*x$published_case_count)/sum(x$published_case_count),published_count_weighted_median_season_week=mt$season_week_index,published_count_weighted_median_source_year=mt$source_year,published_count_weighted_median_source_week=mt$source_week,peak_region_observed_province_count=if(nrow(z))z$region_observed_province_count else NA_integer_,peak_region_total_province_count=if(nrow(z))z$region_total_province_count else NA_integer_,peak_region_observed_province_fraction=if(nrow(z))z$region_observed_province_fraction else NA_real_)})|>dplyr::bind_rows()|>dplyr::arrange(epidemiological_region)
 wins<-dplyr::bind_rows(lapply(c(.5,.8,.9),function(t)windows_c19(nc,t)))|>dplyr::mutate(season_temporal_window_schema_version="1.0.0",season_scope_id=ns$season_scope_id,season_label=ns$season_label,.before=1)
 validate_tied_index_columns_c19(national); validate_tied_index_columns_c19(regional)
 if(nrow(regional)!=5||nrow(wins)!=3||any(wins$window_published_case_share<wins$target_share)||any(national$published_count_weighted_season_week<1|national$published_count_weighted_season_week>52)||national$national_published_row_count!=ns$season_published_row_count||national$national_published_case_count!=ns$season_published_case_count||national$national_observed_week_count!=national_observed_week_count||any(regional$regional_published_row_count!=regional_bases$regional_published_row_count[match(regional$epidemiological_region,regional_bases$epidemiological_region)])||any(regional$regional_published_case_count!=regional_bases$regional_published_case_count[match(regional$epidemiological_region,regional_bases$epidemiological_region)])||any(regional$regional_observed_week_count!=regional_bases$regional_observed_week_count[match(regional$epidemiological_region,regional_bases$epidemiological_region)]))abort_c19("C.19 output reconciliation failed.")
 paths<-c(national=a$season_temporal_national_summary,regional=a$season_temporal_region_summary,wins=a$season_temporal_national_concentration_windows);publish_c19(national,paths[["national"]]);publish_c19(regional,paths[["regional"]]);publish_c19(wins,paths[["wins"]])
 read_descriptor_qa_c19(paths[["national"]],tied_index_columns_c19(national)); read_descriptor_qa_c19(paths[["regional"]],tied_index_columns_c19(regional)); invisible(NULL)
}
if(sys.nframe()==0L)main()
